commands/compile.js

In an effort to track this bot's usage, it'd be a good idea to track daily requests since launch date. This graph can be seen on http://headlinedev.xyz/discord-compiler.
This change doesn't affect any installation other than my own

Implement tracking graph

---

commands/compile.js

The number zero, in discord's imaginary world, is a valid language for syntax highlighting, although no highlights appear to exist for it (???). Thus, the following embed from the bot would fail to include the number zero.
``````
```0
1
```
``````
The code needed to replicate this issue is present below, but this change is also great due to the fact that previous outputs were technically able to activate the embed's syntax highlighting. The new `\n` makes this impossible.
The (now) working test case:
```cpp
#include <iostream>
int main () {
std::cout << '0' << std::endl;
std::cout << '1' << std::endl;
}
```

Fix odd message truncation

---

README.md
WandBox.js
commands/compile.js
commands/languages.js
index.js
statistics.js

Before this change, statistics were tracked in a very hacked way. Code duplication was rampant, and it just wasn't very easy to read, nor was it efficient. I was sitting on these changes for a little while now and figured it's finally time to finish it up, so here we go.
Along with this rework, I've also added a new dependency which is `dblapi.js`. This was done in order to allow us to display our server count directly to our discordbots.org page. (yay!).

Rework statistics tracking methods

---

.gitignore
commands/compile.js
commands/compilers.js
commands/help.js
commands/languages.js
commands/ping.js
commands/servers.js
index.js
package.json

This is a great way (for me) to see what our most popular consumers are, and keep track of new large guilds. This pull request also implements the ability for other, new, commands to be created which are developer restricted. I considered making `!botinfo` restricted, but it contains no information that could be considered sensitive so it will remain public.

Implement Developer-only Commands

---

commands/vote.js

Due to their `help.name` values being the same, this command was overriding the implementation of the ping command via the lexicographic assignment of this block https://github.com/Headline/discord-compiler-bot/blob/master/index.js#L40-L44.
```js
jsfiles.forEach((f, i) => {
let props = require(`./commands/${f}`);
console.log(`${f} command has been loaded!`);
client.commands.set(props.help.name, props);
});
```

Fix vote command overriding ping command

---

index.js

Prior to this change, permissions were not being properly checked due to a regression back when dev permissions were just being created. 
The impact for this bug is very minimal, as statistics show that this command was rarely (if-ever) used by end consumers.

Fix regression in dev permission sys

---

commands/compile.js

A bit more info on the commit message body on why, but suffice to say I screwed it up and `stdin` was no longer being passed correctly, so this is the fix for it.

Fix typo on stdin args of compile.js

---

commands/compile.js

This proposal fixes an issue some users may face where their syntax-highlight-intended language may end up being compiled along with the source.
The example that this fixes is the following
``````
```Java
<code>
```
``````

Capture Upper-case discord languages

---

WandBox.js

- Adds `brokencompilers` list to the `Compilers` class. Any compilers whose name exactly matches a name present in `brokencompilers` will not be loaded for use.
- Implements fix for #15 using the aforementioned change to ignore the broken `ghc-head` Haskell compiler.

Add semi-flexible fix for broken WandBox compilers

---

src/commands/compile.js
src/utils/Wandbox.js

Instead of inspecting using `json.hasOwnProperty`, we can just attempt to access the resource directly and see if we're hitting undefined. This should simplify this section of code.

Remove unneccesary object inspection calls

---

package.json
src/tests/messagetimeout.test.js
src/utils/DiscordMessageMenu.js
src/utils/MessageTimeout.js

Prior to this patch, we were mistakenly rethrowing exceptions into the caller of setTimeout(), instead of doing this; we can handle it ourselves and report it to logging.

Fix unhandled exception & improve async stacktraces

---

src/commands/compile.js

This was a regression from one of the recent patches, fixes #27

Fix TypeError when not tracking stats

---

src/commands/compile.js

Fixes #29 
Simple patch, but it prevents nonsensical errors from being displayed.

Escape program_message output before truncation

---

src/commands/asm.js

Off-by-one error for the search offset that resulted in certain message embed fields from being > 1024 characters. This caused certain requests to fail and left users confused with the resulting error message.

Adjust message split offset to prevent request failures

---

src/commands/compile.js
src/utils/apis/StatisticsTracking.js

This patch goes in tandem with some adjustments to the [statistics website](https://headlinedev.xyz/discord-compiler).
We can now calculate what the compilation failure percentage is for each language.

NPOTB: Add support for tracking failed compilations

---

src/CompilerClient.js
src/commands/compile.js
src/commands/help.js
src/utils/CompilationFixer.js
src/utils/apis/Wandbox.js

This patch is one that I have had in the back of my mind for quite some time. I dislike the idea of modifying user's code without telling them, but the failure rate of Java compilations below is enough reason to motivate me to move forward with this patch.
We now will replace `public class Name {...}` to `class Name {....}` in order to prevent these unnecessary failures. Furthermore, I've created a fairly simple system for further replacements to occur, hopefully there's not many more we'd add, but this is a good start towards decreasing compilation failures

Add CompilationFixer to fix user errors for them

---

src/SupportServer.js
src/commands/utils/MessageRouter.js

This is more for confirmation that blacklists are functioning as intended shorty after their issuance and does not affect bot behavior in any way.

NPOTB: Alert compile-log when blacklisted users attempt commands

---

src/commands/compile.js
src/commands/utils/CompilationParser.js

Fix failed parse when language isn't delimited

---

package-lock.json
package.json
src/CompilerClient.js
src/commands/compilers.js
src/tests/compile.test.js
src/tests/messagetimeout.test.js
src/utils/CompilationFixer.js
src/utils/apis/Godbolt.js

To ensure code quality is preserved for incoming pull requests - we're bringing in eslint support.
Our code quality scanner supplied by deepscan.io allows project analysis using eslint, so I figured I'd give it a shot. Beyond a few erroneous warnings, it seemed to preform well and caught a few non-critical oversights.

NPOTB: Add eslint & preform recommended fixes

---

src/commands/utils/CompilerCommandMessage.js
src/tests/compile.test.js

The parser will now stop searching for additional compiler, stdin, or code url arguments after it hits a line break. 
I'm playing with the idea of dissolving the code block requirement, but I'm not on board yet. The reason I'm hesitant to accept the example request in issue #47 as valid is because the code blocks help distinguish that the code isn't run in any context.
Fixes #47

Fix parsing on missing newln

---

src/index.js

Node.js will spend more time in garbage collection as it reaches this set limit. Lately I've been experimenting with node.js and memory limits, this change is certainly experimental to force garbage collection earlier rather than later.

Set memory limit to 512MB

---

Cargo.lock
Cargo.toml
src/events.rs
src/main.rs
src/stats/statsmanager.rs

This must have slipped my mind - requests tracking on the [site](https://headlinedev.xyz/discord-complier) has not been working for the past few days. Turns out, it was never completely implemented.
This will bring requests collections back

Add support for requests tracking

---

src/commands/invite.rs
src/commands/mod.rs
src/main.rs
src/utls/constants.rs
src/utls/discordhelpers.rs

This is hopefully the last forgotten element to be implemented in v3.
We have references to this command in the presence, but the command hasn't existed so there was some confusion about obtaining the invite link.

Implement invite command

---

src/apis/dbl.rs
src/cache.rs
src/events.rs
src/stats/statsmanager.rs
src/stats/structures.rs

We were not receiving any vote stats top.gg due to the fact that we were binding the webhook on 127.0.0.1 (oops). 
Furthermore, we've had all the information necessary to post server/shard count to top.gg, but it just hasn't been implemented before this patch. Now, top.gg should be receiving everything necessary to accurately track us.

Fix top.gg services issues

---

src/utls/discordhelpers.rs

This is similar to another patch that landed - but this patch standardizes all output truncation to ensure that multi-byte characters are trimmed correctly.

Prevent panic on string truncation

---

src/events.rs

This is directly related to #60, but does not fix the issue completely.
This was simply a copy-paste error that was lost in the noise

Fix server presence count decrement

---

.github/workflows/publish.yml

This will build binaries on windows & linux so installations will not require self-compilation.
Here's to hoping this works on the first try.

Add publish action on new tag

---

.github/workflows/publish.yml

This was a mistake in #62 
We now use the supported [actions OS names](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources).

Fix incorrect OS names in package script

---

.env.example
src/main.rs

Instead of exiting with a panic upon not being able to retrieve our application info, we can recover if we have the bot's user ID. 
The bot's user ID is used to dispatch messages manually and is required to be available through some means, so we can fall back on an optional environment variable here.
This was discovered to be necessary today after a DNS lookup to discord failed.

Recover from failed application info requests

---

Cargo.toml
src/apis/dbl.rs
src/build.rs
src/cache.rs
src/commands/asm.rs
src/commands/block.rs
src/commands/botinfo.rs
src/commands/compile.rs
src/commands/compilers.rs
src/commands/languages.rs
src/commands/unblock.rs
src/events.rs
src/main.rs
src/utls/discordhelpers.rs

Fixes #60 
This patch changes how the our presence is updated. Now, all presence changes are replicated across all shards to prevent any inaccuracies based off of which shard receives the latest event. These were always off-by-one errors, but it was annoying enough to bring this patch in.
I renamed cache elements to __Cache to ensure it's clear to understand exactly what's being accessed from where.
I'm also sneaking in other changes - we're now going to be grabbing git info at compile time, along with some additional documentation on cache stuffs.

Globalize presence updates

---

src/commands/compilers.rs

I'm not entirely sure how this menu was this large - but we're making it smaller now.
[Here](http://i.michaelwflaherty.com/u/hBKjvS0AQD.png)'s an example of the ridiculousness:

Limit compilers menu to 15 items

---

Cargo.lock
Cargo.toml
src/main.rs

Before we were building against a fork of serenity that I kept to contain a fix we needed (https://github.com/serenity-rs/serenity/issues/1023). 
Now that serenity has seen a major version update since then, we can update to latest and stop using our fork.

Build against serenity v0.9

---

src/commands/botinfo.rs

This fixes a regression introduced by #67.
We were grabbing GIT_HASH_SHORT & GIT_HASH_LONG from the environment, but they actually exist as a part of our ConfigCache - uniquely separate from the rest of the members of ConfigCache.

Fix botinfo command regression

---

Cargo.lock
Cargo.toml
src/cache.rs
src/commands/asm.rs
src/commands/compile.rs
src/events.rs

This has been sitting in the back of my head for quite some time - I quite like this feature.
When a user submits a request and then deletes their message, we'll also delete our response embed. Sometimes people make silly mistakes in their requests - and to prevent channel spam they delete their own message, with our message lingering behind.
This patch now prevents that.

Delete response on request deletion

---

src/cache.rs
src/events.rs
src/stats/statsmanager.rs

Instead of relying on the `ServerCountCache`, we will now grab presence server count from the internal stats count held in `StatsManagerCache`.
This will also do away with `ServerCountCache` entirely - as any information about our statistics can be and should be held inside of our StatsManagerCache

Grab guild count from stats value

---

src/utls/parser.rs

It's very possible to get no host when a user enters an invalid URI, and this case was not being handled properly. This patch adds a check for an invalid host and will refuse the request properly instead of panicking.

Fix panic on no host

---

.github/workflows/main.yml

~~This patch should prevent clippy from running on our dependencies which we have no control over.~~
This patch removes night builds and clippy from our CI. I'd love to have clippy running to look for bad patterns, but because we can't select it to analyze only our package, our dependencies are flagging us. Furthermore, nightly rust has issues that could also prevent CI from functioning as intended so we'll only test against stable compilations.

Remove clippy & nightly builds from CI

---

src/utls/constants.rs
src/utls/discordhelpers.rs

Fixes #83 
We can get away with some more space for error output, that way some longer errors can actually be properly displayed. See referenced issue for more details.

Increase allowed length of error messages

---

src/commands/compile.rs
src/utls/discordhelpers.rs

I'm not sure why this wasn't being logged beforehand, but this patch will also log the author's user id on compilation requests.
This makes it easier to block abusive users.

Include author id in complogs

---

src/cache.rs
src/events.rs

This includes the deletion of malformed requests to the bot when the original request is deleted, just as successful requests behave.
We also will increase the size of the LruCache to 25, since that number seems large enough to represent the amount of requests we get.

Include error messages in MessageDeleteCache

---

src/cache.rs
src/commands/asm.rs
src/commands/compile.rs
src/events.rs
src/utls/discordhelpers.rs

Closes #95 
This patch allows users to edit their old requests and the bot will now rerun the code through wandbox or godbolt in order to prevent users from having to send multiple requests to get code to pass.
The implementation is quite crude and points at some underlying issues in regards to organization, where we now have some duplicated code. I'm intentionally adding technical debt here, but this debt will be paid back at a later date.

Allow users to edit recent requests

---

src/commands/asm.rs
src/commands/compile.rs
src/utls/discordhelpers.rs
src/utls/parser.rs

From what I've heard from our users, this is one of the most desired patches. This patch allows users to completely omit the language parameter after the `;compile` command *iff* the user supplies a supported language in discord's syntax highlighting embed.
An example of the new form is as follows:
``````
;compile -O3 -Wall -Werror
```c++
int main() {
}
```
``````
We will also maintain backwards compatibility for the old way. If the first argument after the `;compile` command resolves to a valid language or compiler, then we ignore the language parameter just as we used to.
Having been tested quite thoroughly already, this patch will live on the live bot for some time to ensure no issues arise before merge.

Allow language resolution via syntax highlighting

---

src/commands/cpp.rs
src/commands/help.rs
src/commands/mod.rs
src/cppeval/eval.rs
src/cppeval/mod.rs
src/main.rs
src/utls/discordhelpers.rs

This command creates some shorthand compilation alternatives for quick c++ evaluation. We're going to follow geordi's syntax as it will be familiar for those from IRC and it's quite simple overall. For more information regarding how this command works you can go to http://eel.is/geordi/#syntax
I'll be editing the website to show this command at some point in the future.
Closes #96

Add geordi-like cpp command

---

src/commands/compilers.rs
src/managers/compilation.rs

Fixes #115 
Compiler Explorer will not handle execution requests for all of it's languages. This patch adds Nim to the list of languages we will only run on wandbox.

Migrate Nim compilations back to Wandbox

---

src/cppeval/eval.rs
src/tests/cpp.rs

Fixes #108 
This patch expands bracket detection to ignore different comment styles.

Balance multiline and inline comments

---

src/commands/format.rs

This looks to be a regression from an older commit. Must have been a copy-paste error, but now replied attachment formats should work as expected.

Use the correct attachment in format command replies

---

src/tests/parser.rs
src/utls/parser.rs

This error has been a little troublesome to find, but we've got it.
For requests in the form
``````
.compile c -O3```int main() { }```
``````
We'd not find a new line character and the ` *was* found. Previous logic would fail to update the codeblock start position and we'd eventually end up removing from an empty array.

Fix errors on one line parsing

---

src/cache.rs
src/commands/compile.rs
src/main.rs

This should make the bot easier to self host, I'm not sure why dbl token was required prior to this patch but I believe it's no longer needed.

Add error on .env not found & allow no dbl token

---

src/commands/compilers.rs
src/managers/compilation.rs

Haskell currently defaults to a version of the compiler which requires a dependency Compiler Explorer does not have, this is an issue with the Haskell compiler. Ref: https://github.com/compiler-explorer/compiler-explorer/issues/3418
We'll just hack around this for now.

Temporarily patch Haskell & ignore casing on compilers lookup

---

src/cache.rs
src/commands/asm.rs
src/commands/compile.rs
src/commands/cpp.rs
src/events.rs
src/utls/discordhelpers/mod.rs

Fixes #130
This patch adds the original message sent into our message cache so we can correctly identify message replys

Correctly identify original message replys for edits

---

Cargo.toml
src/cache.rs
src/managers/compilation.rs

Fixes #121 
This patch fixes a minor bug when trying to view assembly output for languages or compiler which are not supported for this feature.
Continue to refer to `;languages` for this support.

Fix unwrap on None value for invalid assembly target

---

src/commands/format.rs
src/slashcmds/format.rs
src/utls/discordhelpers/interactions.rs
src/utls/parser.rs

Closes #129 
This brings in the popular compiler explorer feature that allows folks to include header files into their code compilations by inserting a url instead of a path.

Support include urls

---

src/events.rs
src/managers/stats.rs

The server count available in the Bot's presence is 0 when statistics tracking is not enabled. This patch changes our tracking strategy to also consider guild counts even when statistics aren't being posted.

Allow server count presence to show when stats are disabled

---

.env.example
src/commands/asm.rs
src/commands/compile.rs
src/commands/cpp.rs
src/main.rs
src/utls/discordhelpers/mod.rs

This patch changes how we handle the removal of reactions, a long overdue change which allows us to no longer require the manage messages permissions.
Thanks to erik and brain for recommending this change
Server owners are now recommended to disable this permission on the bot.
If you see an invite link that does not have the permissions value of `379968` please let me know, I've went ahead and changed every invite link location I could find, but it's possible I missed one.
This patch also ensures that the optional environment variables in .env are truly optional.

Remove necessity for manage messages permission

---

src/utls/parser.rs

This was a common headache for some - previously we assumed that replying to messages only made sense if that replied message served a purpose for us. We operated under the assumption that any compilation with a reply means that the reply message contains code. Here we dismantle that assumption.
If the replied to message *does* have a codeblock and the executor's message also has one we will continue to assume that the executor's codeblock is stdin and the reply message codeblock is the code.

Allow users to reply to messages without codeblocks

---

src/tests/parser.rs
src/utls/parser.rs

Continuing with our theme on improving replies today, this patch fixes an issue where the parser would fail to detect command line arguments and instead interpret them as options. 
Fixes #144

Fix argument endpoint detection on replies

---

Cargo.toml
src/events.rs
src/managers/command.rs

We only need to register application commands once, not per shard. This speeds up some boot time and adds early exit logic for command registration if it's happened already.
Thanks to eirk#7057 for pointing this out.

Register application commands once

---

src/utls/constants.rs
src/utls/discordhelpers/embeds.rs

Fixes #148 
Godbolt requests were limiting their error output by the wrong constant length, but we've also increased the error output length for languages like python which may have verbose traceback errors

Increase error output length & correct compiler-explorer error lengths

---

Cargo.toml
src/boilerplate/c.rs
src/boilerplate/cpp.rs
src/boilerplate/generator.rs
src/boilerplate/java.rs
src/boilerplate/mod.rs
src/tests/boilerplate/cpp.rs
src/tests/boilerplate/java.rs
src/tests/boilerplate/mod.rs
src/tests/mod.rs
src/utls/constants.rs

Fixes #152 
This is an extension to the boilerplate implementation, we'll see a few things developed on this branch.
This patch will move some of the regex creation to be in the `constants.rs` and prevent regex recompilation after every compilation request, something that we needed to bring `lazy_static` in to accomplish.
Our end goal is to move function declarations out of main methods, that way functions can be created and moved to their correct places as needed.
We'll need a regex made that allows us to detect function definitions. Unlike our main regexes, we'd need to match functions that could have templated/generic return types. Let's use C++ as an example.
```cpp
std::vector < int > myfunc(int a, int b) {
return std::vector{a, b};
}
for (auto i : myfunc(3, 5)) {
std::cout << i << …
```

Improve boilerplate implementation

---

src/managers/compilation.rs
src/utls/constants.rs
src/utls/parser.rs

This is a common pain point for newer Java users, we'll just automatically remove the `public` keyword from class definitions to ensure their code compiles.

Fix java compilations with public keyword

---

Cargo.toml
src/events.rs
src/managers/command.rs
src/managers/compilation.rs
src/slashcmds/diff.rs
src/slashcmds/mod.rs
src/utls/constants.rs
src/utls/discordhelpers/mod.rs

This command (implemented as a slash command) allows users to diff code-blocks as they wish.
Sometimes it's difficult to quickly identify changes people make between posts, so this command will help isolate those changes in a diff format.

Implement command to allow diffing code-blocks

---

src/events.rs
src/main.rs
src/managers/command.rs

This patch will automatically register commands on a per-guild basis if built in debug mode. This is useful for speeding up command development workflow.
Furthermore, we'll identify commands registered per guild in the `Apps >` dropdown by specifying that it is a `[BETA]` command. This became quite confusing in situations where both the development bot and the live bot exist within the same server.

Register commands differently based off debug or release builds

---

src/utls/discordhelpers/mod.rs

This was a regression from #141, I missed a case.
This lead to the bot leaving it's previous reaction emoji if a compilation request was edited.

Remove emojis from compilation edits properly w/o manage messages

---

.rusty-hook.toml
src/boilerplate/generator.rs
src/boilerplate/mod.rs
src/boilerplate/php.rs
src/utls/constants.rs
src/utls/discordhelpers/mod.rs

This patch brings in the adding the php preamble as a boilerplate generator, in case the user didn't supply one.
I also fixed a bug where some compilations were falsely detected as not containing their main methods when they actually were. This was caused by the regex always consuming the next character when a `"` was found.

Add php boiler plate generation & fix boilerplate detect on empty string literal

---

src/tests/boilerplate/cpp.rs
src/tests/boilerplate/java.rs

Fixes #162 .. kinda
#162 was fixed by #160, but due to a configuration error, the change was never deployed.
This patch adds some forgotten tests and should correctly trigger deployment

Add more bplate test coverage for C++ & Java

---

src/cache.rs
src/events.rs
src/managers/command.rs
src/slashcmds/diff.rs
src/slashcmds/diff_msg.rs
src/slashcmds/mod.rs
src/utls/discordhelpers/interactions.rs

This patch brings in the diff functionality as a message command, allowing users to run diffs without having to copy message IDs.
We've also changed the parsing mechanism to grab input from code blocks if it exists, but if there's no code block found it will instead use message content.

Implement diff as message command

---

.env.example
src/main.rs
src/utls/discordhelpers/embeds.rs

This patch will log any panics to a new #panic-log channel in our support discord. This should allow for faster error identification, preventing me from monitoring logs manually.

Add support to log panics to chat for conveinence

---

src/commands/compilers.rs
src/commands/format.rs
src/commands/formats.rs
src/commands/languages.rs
src/managers/compilation.rs
src/slashcmds/format.rs
src/utls/discordhelpers/interactions.rs

This patch should prevent the situation we ran into today where wandbox.org was down for a few hours, which prevented us from functioning at all. Now, we will continue with boot if a service was unable to load and at least retain partial service availability.

Allow boot with partial service availability

---

src/events.rs

This fixes an unwrap leading to a panic that was discovered while debugging today's api outages.
```
panicked at 'called `Option::unwrap()` on a `None` value', src/events.rs:109:50
```

Don't assume DblCache exists

---

src/utls/discordhelpers/mod.rs

Sometimes wandbox will not report a status leading to this call not finding any color on the embed.
If we do not get a status from wandbox assume the compilation failed

Assume status-less wandbox compilations are not successful

---

src/commands/compile.rs
src/commands/cpp.rs
src/managers/compilation.rs
src/slashcmds/cpp.rs
src/utls/discordhelpers/embeds.rs

This patch allows users to see the language and compiler used for all compilation and assembly requests.
This is useful to understand what default compilers are being used along with what languages others are using for their requests.

Add more compilation information to footer for compilations

---

src/managers/compilation.rs

This is quite the funny bug, we weren't sanitizing user targets which allowed folks to @ users (and everyone) on the bot.

Prevent users from @'ing through invalid targets

---

src/boilerplate/c.rs

This patch is a regression from #154, C implementation encountered some mindless copy-paste errors.

Fix C printf boilerplate

---

src/managers/compilation.rs
src/utls/parser.rs

- Makes TypeScript use [wandbox](https://wandbox.org) instead of [godbolt](https://godbolt.org/)
- Adds the `ts` shorthand for `typescript`

TypeScript fix & shorthand `ts`

---

src/boilerplate/c.rs
src/boilerplate/cpp.rs
src/boilerplate/csharp.rs
src/boilerplate/java.rs
src/commands/asm.rs
src/commands/compile.rs
src/commands/formats.rs
src/cppeval/eval.rs
src/events.rs
src/managers/compilation.rs
src/slashcmds/diff.rs
src/tests/cpp.rs
src/tests/mod.rs
src/tests/parser.rs
src/utls/discordhelpers/embeds.rs
src/utls/discordhelpers/mod.rs
src/utls/parser.rs

this comes from:
```ps1
cargo clippy --all-targets --all-features -- -D clippy::all
```
- found many `.push_str(format!(...))` and replaced them with `writeln!(...)`
- some unnecessary `return {...};` (removed "return" and ";")
- `.get(0)` becomes `.first()` on `Vec<>`

Trying to comply with new `cargo clippy`

---

src/main.rs
src/utls/parser.rs

Fixes #165 
Wandbox's compilations for bash would fail to identify `bash` as a language and instead would fallback on a compiler entitled `bash`. This change properly aliases `bash` to `Bash Script` so language lookup can succeed when needed.

Add bash alias to fully qualify wandbox.org name

---

src/utls/discordhelpers/embeds.rs

A missing check was added to prevent panicking on results from godbolt.org without a build result

Check for existence of build result 

---

src/utls/discordhelpers/embeds.rs

Fixes an oversight #193 
Implements the same output sanitation methods used in `;compile` command in `;asm`

Prevent users from bypassing codeblock with embedded back-tick chars

---

src/utls/parser.rs

Adds the following shorthands:
- `cpp`, `hpp`, and `h++` for c++.
- `h` for c.
- `csharp` and `cs` for c#.
- `bash` and `sh` for bash script.
- `rb` for ruby.
- `kt` for kotlin.
- `golang` for go.
- `fs` and `f#` for f sharp.
- `hs` and `lhs` for haskell.
- `jl` for julia.
- `gvy` for groovy.

Added more language shorthands.

---

Cargo.toml
src/utls/discordhelpers/embeds.rs

This was a regression introduced by 6c397b7.
The length limit for external strings is less than discord's embed limit, so we'd unintentionally truncate assembly requests.
Fixes #195

Do not conform asm as external strings

---

Cargo.toml
src/cache.rs
src/commands/asm.rs
src/commands/botinfo.rs
src/commands/compile.rs
src/commands/cpp.rs
src/commands/formats.rs
src/commands/help.rs
src/commands/invite.rs
src/events.rs
src/managers/command.rs
src/slashcmds/asm.rs
src/slashcmds/compile.rs
src/slashcmds/cpp.rs
src/slashcmds/diff.rs
src/slashcmds/diff_msg.rs
src/slashcmds/format.rs
src/slashcmds/help.rs
src/slashcmds/invite.rs
src/slashcmds/ping.rs
src/utls/discordhelpers/interactions.rs
src/utls/discordhelpers/menu.rs
src/utls/discordhelpers/mod.rs

This brings us up to date on Serenity and a few of our other dependencies. 
No features for this patch, but lots of refactoring to get us away from deprecated Serenity functionality. I do not follow Serenity too closely, but I suspect more breakage in the future and would like to remain at least somewhat up to date.

Update dependencies and Rust toolchain version

---

src/commands/asm.rs
src/commands/compile.rs
src/commands/cpp.rs
src/commands/formats.rs
src/commands/help.rs
src/commands/invite.rs
src/events.rs
src/slashcmds/format.rs
src/utls/discordhelpers/embeds.rs

Before dartformat and gofmt were added to compiler-explorer, we assumed all formatters would have styling options. This patch fixes that issue. Fixes #192 
I've also moved a bunch of message dispatching off to it's own function, it's especially important as we send embeds in a way Serenity does not quite expect. Future breakages may be possible, keeping this in one spot will make updating easier.

Clean up embed dispatching and fix formatters with no style options

---

Cargo.toml
src/commands/asm.rs
src/commands/compile.rs
src/commands/cpp.rs
src/events.rs
src/managers/compilation.rs
src/slashcmds/cpp.rs
src/utls/discordhelpers/embeds.rs
src/utls/discordhelpers/mod.rs

This is a feature request from the #include discord server, it adds a button for users to view their request on godbolt.org. 
The button gets updated on edits, everything should perform as expected. If there are any odd behaviors or configurations that are not represented after clicking the link please file an issue.

Create "View on Godbolt" button

---

src/cache.rs
src/commands/compile.rs
src/events.rs
src/slashcmds/diff_msg.rs

This patch is an attempt at lowering lock contention. Special attention was placed on `Mutex`es and `RwLock::write()`s. 
There is likely a deadlock somewhere, #201 will track this, but I'll do what I can to clean up now with this PR and we'll see how this patch performs..

Ensure locks are closed as soon as possible

---

src/events.rs

As reported by BlckLight, this fixes a regression introduced in #202. Attention wasn't taken to ensure that the checks for our final shard is executed properly. This issue caused the last shard spawn to be flagged as a duplicate ready event. Here we simply restore the proper order of operations.

Fix all_shards_ready check ordering

---

Cargo.toml
src/cppeval/eval.rs
src/utls/constants.rs
src/utls/parser.rs

Let's take one at a time
- Limiting regular expression compilations
- We already had some "static" regular expressions so we don't waste time recompiling expressions, but for some reason our hottest code path was not utilizing this. After this patch, every regular expression is now compiled only once.
- Geordi errors
- I've seen many times where our `;cpp` command gets confused for `;compile`. This confusion makes sense, our system is not the most intuitive here. This patch creates a friendly warning that `;cpp` is meant for geordi-like input and they may want to use `;compile` instead.
- There's more to this error, I'm curious if our best strategy moving forward will be to import all programming languages as valid commands, so languages like java can be executed without `;compile java` …

Limit Regex compilations, improve geordi errors, production release profile

---

src/managers/compilation.rs

Switches JavaScript to use Wandbox instead of GodBolt; GodBolt has weird issues and includes a `print` function? Also GodBolt doesn't support some node things like `fs` or `setTimeout`

Switch JavaScript to use Wandbox instead of GodBolt

---

src/cache.rs
src/commands/asm.rs
src/commands/compile.rs
src/events.rs
src/managers/compilation.rs
src/tests/mod.rs
src/utls/discordhelpers/embeds.rs
src/utls/discordhelpers/mod.rs

What was happening was that a malformed embed structure was causing silent failures during the handling in the edit message code path. Now all errors here will bubble up back to the user.
The source issue was the the EditMessage struct was being created with an empty button (godbolt link) for wandbox requests, causing an error from discord asking for a non-empty component

Allow edit failures to be dispatched to users as an internal error, prevent empty components on embed send
