menus.js

Old reaction collectors sat in memory forever, this pull request shuts them down after 30 seconds of inactivity. Should hopefully save some memory with this one.

Add timeouts to reaction collectors

---

WandBox.js
commands/compile.js
index.js
supportserver.js

This allows us to monitor what kind of requests we receive for statistics reasons, along with monitoring for abuse.

Add compilation monitoring

---

commands/compile.js

This feature allows pulling code to execute from some online paste tool such as Hastebin, or Pastebin.
The way I've implemented this is by adding another special character, in this case, to keep it somewhat in the spirit of Bash (as with the pipe character already used to pass input `|`), I've used `<`, the redirection input character to pass in the URL. An example would be:
```
;compile javascript < https://hastebin.com/raw/kixigahite
```
I've implemented this because a few days ago I wanted to show some Linked List implementation I wrote in JavaScript, and I couldn't because the code ended up being longer than 2000 characters, the limit for Discord's messages. This allows just having the bot pull the code from some online paste tool and run it, no matter if it goes over 2000 characters, …

Add an online file input code option to compile

---

src/SupportServer.js

This would've been an error if it fell into this statement, so just remove it.

Removed unnecessary else statement

---

src/commands/compile.js
src/tests/compile.test.js

This allows us to test how the compiler is building embed; more comprehensive testing to come but this should supply a baseline.

Add compiler response embed testing

---

src/utils/DiscordMessageMenu.js

Block message handling for single page menus

---

src/commands/blacklist.js
src/commands/unblacklist.js

Just some bad language here that needed to be tweaked. Originally this feature was only to blacklist a guild's snowflake, but since has been altered to allow certain users to be blacklisted as well.

NPOTB: Adjust blacklist UI phrasing

---

src/commands/asm.js
src/commands/help.js
src/tests/messagetimeout.test.js
src/utils/CompilationFixer.js

Ran an analysis on the code and discovered a few issues that should be addressed. This patch papers over everything awful (and a few nit picks)

Fix various non-critical regressions

---

.gitignore
Cargo.lock
Cargo.toml
src/cache.rs
src/commands/block.rs
src/commands/mod.rs
src/commands/unblock.rs
src/events.rs
src/main.rs
src/utls/blocklist.rs
src/utls/mod.rs

I enjoyed this feature in v2 and believe it should be implemented here.
I don't believe we had any users on the live bot's blocklist, but this is for peace of mind that any abuse can be handled quickly.

Implement guild/user blocklist

---

Cargo.lock
Cargo.toml
src/commands/asm.rs
src/commands/compile.rs
src/events.rs
src/utls/constants.rs
src/utls/parser.rs

This patch implements a list of accepted paste urls. Anything that is not specified is immediately blocked with a user-facing error.

Allowlist code URL requests

---

.github/workflows/main.yml

Here's to hoping this works as expected.

Cache cargo dependencies for faster build times

---

src/README.md

This also serves as a small test for #71

NPOTB: Create readme for project file structure in src/

---

src/events.rs

This was a regression from #67.
I forgot to update the ready event, so only the last shard spawned would have the presence set.

Fix presence not being set on startup

---

src/commands/compile.rs
src/utls/discordhelpers.rs

Closes #85 
This patch brings some more technical complexity into the compile command, but allows users to see large outputs across multiple pages. We'll be bringing this change into production fairly quickly for a public test cycle as main code paths for small outputs are preserved and unaffected. 
Assuming all is well during that we should be able to get this in-tree fairly quickly.

Add support for large outputs

---

Cargo.toml
discord-compiler.iml
src/cache.rs
src/commands/asm.rs
src/commands/compile.rs
src/events.rs
src/main.rs
src/slashcmds/format.rs
src/utls/discordhelpers/interactions.rs
src/utls/discordhelpers/menu.rs
src/utls/discordhelpers/mod.rs

This switches us to the new API version from discord (v10).

Pin Serenity to version 0.11.1 & bump our version

---

src/events.rs
src/utls/discordhelpers/interactions.rs

This patch simply covers some unexpected rough edges and assumptions, that's all.

A couple unwrap fixes

---

src/cppeval/eval.rs

More cargo clippy fixes.
Every time I run clippy I embarrass myself 😄

Remove redundant error case checking

---

src/commands/cpp.rs
src/events.rs
src/utls/parser.rs

This is a lump of a few patches for some active issues
Fixes #216 #214 #212 #211

Fall Fixes

---

src/commands/cpp.rs

gcc 10.1 -> gcc trunk
-O2 -> -O3
-std=gnu++2a -> -std=gnu++26

Change compiler and options for ;cpp

---

src/boilerplate/dart.rs
src/boilerplate/generator.rs
src/boilerplate/mod.rs

Add boilerplate for dart
